-- Shop Owner Profiles Data Export
-- Generated on: 2026-01-24 07:51:07
-- Total profiles: 5

USE goplay_sports_platform;

INSERT INTO shop_owner_profiles (`id`, `user_id`, `shop_name`, `business_name`, `business_registration_number`, `tax_identification_number`, `business_type`, `year_established`, `number_of_employees`, `business_phone`, `business_email`, `shop_address`, `shop_city`, `shop_state`, `shop_postal_code`, `business_description`, `product_categories`, `brand_names`, `website_url`, `facebook`, `instagram`, `twitter`, `shop_logo`, `business_license_document`, `tax_document`, `shop_images`, `bank_name`, `bank_account_number`, `bank_account_holder`, `bank_branch`, `bank_swift_code`, `delivery_options`, `operating_hours`, `return_policy`, `warranty_policy`, `total_products`, `total_sales`, `total_revenue`, `average_rating`, `total_reviews`, `profile_completion_percentage`, `status`, `created_at`, `updated_at`)
VALUES (1, 16, 'GoPlay Sports Hub', 'GoPlay Sports Hub (Pvt) Ltd', 'PV123456', 'VAT123456789', 'sole_proprietor', 2016, 2, '0721842902', 'shopowner1@goplay.lk', '135, galle road', 'colombo', NULL, '10300', 'GoPlay Sports Hub is a retail sports equipment store providing high-quality gear for cricket, football, badminton, and fitness enthusiasts. We offer both in-store and online purchasing with reliable delivery across Sri Lanka.
', NULL, 'nike,puma', NULL, NULL, NULL, NULL, 'uploads/shop-owners/16/logo.png', NULL, NULL, NULL, 'sampath bank', '4230423452354567', 'rohan Gunarathne', 'maharagama', NULL, NULL, NULL, NULL, NULL, 0, 0, 0.00, 0.00, 0, 74, 'active', '2026-01-24 10:32:51', '2026-01-24 13:08:51');

INSERT INTO shop_owner_profiles (`id`, `user_id`, `shop_name`, `business_name`, `business_registration_number`, `tax_identification_number`, `business_type`, `year_established`, `number_of_employees`, `business_phone`, `business_email`, `shop_address`, `shop_city`, `shop_state`, `shop_postal_code`, `business_description`, `product_categories`, `brand_names`, `website_url`, `facebook`, `instagram`, `twitter`, `shop_logo`, `business_license_document`, `tax_document`, `shop_images`, `bank_name`, `bank_account_number`, `bank_account_holder`, `bank_branch`, `bank_swift_code`, `delivery_options`, `operating_hours`, `return_policy`, `warranty_policy`, `total_products`, `total_sales`, `total_revenue`, `average_rating`, `total_reviews`, `profile_completion_percentage`, `status`, `created_at`, `updated_at`)
VALUES (2, 17, 'ProActive Sports Store', 'ProActive Sports Solutions', 'BR-2019-88921', 'VAT987654321', 'sole_proprietor', 2013, 1, '0754138232', 'shopowner2@goplay.lk', 'No. 112, Kandy Road, Wattala', 'wattala', NULL, '11300', 'ProActive Sports Store specializes in sports equipment, apparel, and accessories for schools, clubs, and individual athletes. We provide affordable, durable products and fast delivery services across Sri Lanka.
', NULL, 'nike, wish, puma', NULL, NULL, NULL, NULL, 'uploads/shop-owners/17/logo.jpg', NULL, NULL, NULL, 'sampath bank', '423042345236479', 'priya mendis', 'piliyandala', NULL, NULL, NULL, NULL, NULL, 0, 0, 0.00, 0.00, 0, 74, 'active', '2026-01-24 11:14:34', '2026-01-24 13:15:17');

INSERT INTO shop_owner_profiles (`id`, `user_id`, `shop_name`, `business_name`, `business_registration_number`, `tax_identification_number`, `business_type`, `year_established`, `number_of_employees`, `business_phone`, `business_email`, `shop_address`, `shop_city`, `shop_state`, `shop_postal_code`, `business_description`, `product_categories`, `brand_names`, `website_url`, `facebook`, `instagram`, `twitter`, `shop_logo`, `business_license_document`, `tax_document`, `shop_images`, `bank_name`, `bank_account_number`, `bank_account_holder`, `bank_branch`, `bank_swift_code`, `delivery_options`, `operating_hours`, `return_policy`, `warranty_policy`, `total_products`, `total_sales`, `total_revenue`, `average_rating`, `total_reviews`, `profile_completion_percentage`, `status`, `created_at`, `updated_at`)
VALUES (3, 18, NULL, NULL, NULL, NULL, 'sole_proprietor', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0.00, 0.00, 0, 10, 'active', '2026-01-24 12:05:52', '2026-01-24 12:05:52');

INSERT INTO shop_owner_profiles (`id`, `user_id`, `shop_name`, `business_name`, `business_registration_number`, `tax_identification_number`, `business_type`, `year_established`, `number_of_employees`, `business_phone`, `business_email`, `shop_address`, `shop_city`, `shop_state`, `shop_postal_code`, `business_description`, `product_categories`, `brand_names`, `website_url`, `facebook`, `instagram`, `twitter`, `shop_logo`, `business_license_document`, `tax_document`, `shop_images`, `bank_name`, `bank_account_number`, `bank_account_holder`, `bank_branch`, `bank_swift_code`, `delivery_options`, `operating_hours`, `return_policy`, `warranty_policy`, `total_products`, `total_sales`, `total_revenue`, `average_rating`, `total_reviews`, `profile_completion_percentage`, `status`, `created_at`, `updated_at`)
VALUES (4, 19, NULL, NULL, NULL, NULL, 'sole_proprietor', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0.00, 0.00, 0, 10, 'active', '2026-01-24 12:05:52', '2026-01-24 12:05:52');

INSERT INTO shop_owner_profiles (`id`, `user_id`, `shop_name`, `business_name`, `business_registration_number`, `tax_identification_number`, `business_type`, `year_established`, `number_of_employees`, `business_phone`, `business_email`, `shop_address`, `shop_city`, `shop_state`, `shop_postal_code`, `business_description`, `product_categories`, `brand_names`, `website_url`, `facebook`, `instagram`, `twitter`, `shop_logo`, `business_license_document`, `tax_document`, `shop_images`, `bank_name`, `bank_account_number`, `bank_account_holder`, `bank_branch`, `bank_swift_code`, `delivery_options`, `operating_hours`, `return_policy`, `warranty_policy`, `total_products`, `total_sales`, `total_revenue`, `average_rating`, `total_reviews`, `profile_completion_percentage`, `status`, `created_at`, `updated_at`)
VALUES (5, 20, NULL, NULL, NULL, NULL, 'sole_proprietor', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0.00, 0.00, 0, 10, 'active', '2026-01-24 12:05:52', '2026-01-24 12:05:52');


